import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from 'next/font/google';
import { Toaster } from 'sonner'
import { ThemeProvider } from "@/components/theme-provider";



const roboto = Roboto({
  subsets: ['latin'], // Specify the character subsets you need
  weight: ['400', '700'], // Specify font weights if needed
  style: ['normal', 'italic'], // Specify font styles if needed
});


export const metadata: Metadata = {
  title: "Soy and Spice | Seasonal Restaurant & Scratch Bar",
  description: "Generated by create next app",
  icons: {
    icon: "/mainLogo.jpg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased`}
      >
        <Toaster richColors />
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
